/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC_DelSig.h"
#include "Out2_1_aliases.h"
#include "Out2_1.h"
#include "Out1_2_aliases.h"
#include "Out1_2.h"
#include "Out1_1_aliases.h"
#include "Out1_1.h"
#include "UART_TX_aliases.h"
#include "UART_TX.h"
#include "UART_RX_aliases.h"
#include "UART_RX.h"
#include "isr_UART.h"
#include "UART_1.h"
#include "DMA_1_dma.h"
#include "isr_Filter_End.h"
#include "TIA.h"
#include "Filter_1.h"
#include "Filter_1_PVT.h"
#include "DMA_2_dma.h"
#include "EN_1_aliases.h"
#include "EN_1.h"
#include "EN_2_aliases.h"
#include "EN_2.h"
#include "ADC_DelSig_AMux.h"
#include "ADC_DelSig_Ext_CP_Clk.h"
#include "ADC_DelSig_IRQ.h"
#include "ADC_DelSig_theACLK.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

